package fun.ogi.module.theme;



import fun.ogi.util.render.providers.ColorProvider;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

public class ThemePresets {
    public static List<Theme> getAllPresets() {
        List<Theme> list = new ArrayList<>();
        list.add(createAstolfo());
        list.add(createNeonPurple());
        list.add(createCrimson());
        list.add(createOcean());
        list.add(createSunset());
        list.add(createEmerald());
        list.add(createSakura());
        list.add(createMidnight());
        list.add(createCottonCandy());
        list.add(createRgbDynamic());
        list.add(createLava());
        list.add(createArctic());
        list.add(createToxic());
        list.add(createAmethyst());
        list.add(createChocolate());
        list.add(createBloodMoon());
        list.add(createCyberpunk());
        list.add(createAurora());
        list.add(createHarvest());
        list.add(createVoid());
        return list;
    }

    private static Theme createAstolfo() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(255, 85, 185).getRGB());
        p.setSecondary(new Color(185, 85, 160).getRGB());
        p.setTertiary(new Color(85, 185, 160).getRGB());
        p.setBackground(new Color(15, 12, 20).getRGB());
        p.setSurface(new Color(25, 20, 35).getRGB());
        p.setTextPrimary(new Color(255, 255, 160).getRGB());
        p.setTextSecondary(new Color(160, 140, 180).getRGB());
        p.setTextAccent(new Color(220, 180, 160).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(new Color(255, 255, 160).getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(20, 15, 30, 255).getRGB());
        p.setTargetHudHealth(new Color(255, 85, 185).getRGB());
        p.setTargetHudAccent(new Color(185, 85, 160).getRGB());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(new Color(255, 85, 185).getRGB());
        p.setSpirits(new Color(185, 85, 160).getRGB());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.28f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.55f));
        p.setGlow(new Color(255, 85, 185, 255).getRGB());
        p.setBlurColor(new Color(25, 20, 35, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getSecondary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(50, 40, 60).getRGB());
        p.setToggleOn(new Color(255, 85, 185).getRGB());
        p.setToggleOff(new Color(140, 60, 100).getRGB());
        p.setNotificationSuccess(new Color(100, 255, 150).getRGB());
        p.setNotificationError(new Color(255, 70, 70).getRGB());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(40, 30, 50, 255).getRGB());
        p.setNametagHealth(new Color(255, 80, 80).getRGB());
        p.setParticlePrimary(new Color(255, 85, 185).getRGB());
        p.setCategoryCombat(new Color(255, 80, 80).getRGB());
        p.setCategoryMovement(new Color(100, 255, 120).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(255, 255, 80).getRGB());
        p.setCategoryWorld(new Color(185, 85, 160).getRGB());
        p.setRainbow(false);
        p.setAnimated(true);
        p.setSpeed(0.8f);
        p.setGlowIntensity(1.2f);
        p.setSaturation(1.0f);
        p.setBrightness(1.0f);
        return new Theme("Astolfo", "Pastel rainbow with pink/purple tones", p);
    }

    private static Theme createNeonPurple() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(160, 50, 255).getRGB());
        p.setSecondary(new Color(80, 200, 255).getRGB());
        p.setTertiary(new Color(255, 50, 255).getRGB());
        p.setBackground(new Color(10, 8, 18).getRGB());
        p.setSurface(new Color(20, 15, 30).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(140, 130, 160).getRGB());
        p.setTextAccent(new Color(180, 140, 160).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(15, 10, 25, 255).getRGB());
        p.setTargetHudHealth(new Color(255, 50, 255).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getSecondary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.25f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.50f));
        p.setGlow(new Color(160, 50, 255, 255).getRGB());
        p.setBlurColor(new Color(20, 15, 30, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getSecondary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(40, 30, 50).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(100, 50, 140).getRGB());
        p.setNotificationSuccess(new Color(80, 255, 160).getRGB());
        p.setNotificationError(new Color(255, 60, 60).getRGB());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(30, 20, 45, 255).getRGB());
        p.setNametagHealth(new Color(255, 80, 80).getRGB());
        p.setParticlePrimary(new Color(255, 50, 255).getRGB());
        p.setCategoryCombat(new Color(255, 80, 80).getRGB());
        p.setCategoryMovement(new Color(80, 255, 100).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(255, 255, 80).getRGB());
        p.setCategoryWorld(p.getSecondary());
        p.setAnimated(false);
        p.setGlowIntensity(1.5f);
        return new Theme("Neon Purple", "Bright purple with cyan accents", p);
    }

    private static Theme createCrimson() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(220, 30, 50).getRGB());
        p.setSecondary(new Color(180, 60, 30).getRGB());
        p.setTertiary(new Color(255, 120, 50).getRGB());
        p.setBackground(new Color(12, 8, 10).getRGB());
        p.setSurface(new Color(25, 15, 18).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(160, 120, 120).getRGB());
        p.setTextAccent(new Color(255, 160, 140).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(20, 10, 12, 255).getRGB());
        p.setTargetHudHealth(new Color(255, 60, 60).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(new Color(255, 100, 50).getRGB());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.20f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.45f));
        p.setGlow(new Color(220, 30, 50, 255).getRGB());
        p.setBlurColor(new Color(25, 15, 18, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getTertiary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(50, 30, 30).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(120, 40, 40).getRGB());
        p.setNotificationSuccess(new Color(80, 200, 80).getRGB());
        p.setNotificationError(p.getPrimary());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(40, 20, 22, 255).getRGB());
        p.setNametagHealth(new Color(255, 60, 60).getRGB());
        p.setParticlePrimary(new Color(220, 30, 50).getRGB());
        p.setCategoryCombat(p.getPrimary());
        p.setCategoryMovement(new Color(100, 220, 100).getRGB());
        p.setCategoryRender(new Color(255, 120, 50).getRGB());
        p.setCategoryPlayer(new Color(255, 200, 80).getRGB());
        p.setCategoryWorld(new Color(180, 60, 150).getRGB());
        return new Theme("Crimson", "Dark red theme with warm accents", p);
    }

    private static Theme createOcean() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(0, 180, 220).getRGB());
        p.setSecondary(new Color(0, 230, 180).getRGB());
        p.setTertiary(new Color(50, 120, 255).getRGB());
        p.setBackground(new Color(8, 14, 22).getRGB());
        p.setSurface(new Color(14, 22, 32).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(120, 160, 180).getRGB());
        p.setTextAccent(new Color(100, 200, 160).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(10, 18, 28, 255).getRGB());
        p.setTargetHudHealth(new Color(0, 230, 180).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getSecondary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.30f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.55f));
        p.setGlow(new Color(0, 180, 220, 255).getRGB());
        p.setBlurColor(new Color(14, 22, 32, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getTertiary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(20, 40, 50).getRGB());
        p.setToggleOn(p.getSecondary());
        p.setToggleOff(new Color(30, 80, 100).getRGB());
        p.setNotificationSuccess(new Color(80, 220, 160).getRGB());
        p.setNotificationError(new Color(255, 70, 70).getRGB());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(18, 30, 42, 255).getRGB());
        p.setNametagHealth(new Color(0, 230, 180).getRGB());
        p.setParticlePrimary(new Color(0, 180, 220).getRGB());
        p.setCategoryCombat(new Color(255, 80, 80).getRGB());
        p.setCategoryMovement(p.getSecondary());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(255, 220, 80).getRGB());
        p.setCategoryWorld(new Color(100, 80, 255).getRGB());
        p.setAnimated(true);
        p.setSpeed(0.5f);
        return new Theme("Ocean", "Deep blue ocean with teal accents", p);
    }

    private static Theme createSunset() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(255, 140, 50).getRGB());
        p.setSecondary(new Color(255, 70, 100).getRGB());
        p.setTertiary(new Color(200, 80, 255).getRGB());
        p.setBackground(new Color(18, 12, 16).getRGB());
        p.setSurface(new Color(30, 18, 22).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(180, 140, 140).getRGB());
        p.setTextAccent(new Color(255, 180, 140).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(22, 14, 18, 255).getRGB());
        p.setTargetHudHealth(new Color(255, 70, 100).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getTertiary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.25f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.50f));
        p.setGlow(new Color(255, 140, 50, 255).getRGB());
        p.setBlurColor(new Color(30, 18, 22, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getTertiary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(50, 30, 35).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(120, 60, 50).getRGB());
        p.setNotificationSuccess(new Color(100, 220, 100).getRGB());
        p.setNotificationError(new Color(255, 60, 60).getRGB());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(40, 22, 28, 255).getRGB());
        p.setNametagHealth(new Color(255, 70, 100).getRGB());
        p.setParticlePrimary(new Color(255, 140, 50).getRGB());
        p.setCategoryCombat(new Color(255, 80, 80).getRGB());
        p.setCategoryMovement(new Color(100, 230, 100).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(255, 220, 80).getRGB());
        p.setCategoryWorld(p.getTertiary());
        return new Theme("Sunset", "Warm orange and pink sunset tones", p);
    }

    private static Theme createEmerald() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(50, 220, 120).getRGB());
        p.setSecondary(new Color(30, 180, 255).getRGB());
        p.setTertiary(new Color(100, 255, 80).getRGB());
        p.setBackground(new Color(8, 18, 12).getRGB());
        p.setSurface(new Color(14, 26, 18).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(130, 180, 150).getRGB());
        p.setTextAccent(new Color(140, 255, 180).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(10, 22, 14, 255).getRGB());
        p.setTargetHudHealth(new Color(50, 220, 120).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getSecondary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.30f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.55f));
        p.setGlow(new Color(50, 220, 120, 255).getRGB());
        p.setBlurColor(new Color(14, 26, 18, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getSecondary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(20, 40, 30).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(30, 90, 60).getRGB());
        p.setNotificationSuccess(p.getPrimary());
        p.setNotificationError(new Color(255, 60, 60).getRGB());
        p.setNotificationInfo(p.getSecondary());
        p.setNametagBackground(new Color(18, 34, 22, 255).getRGB());
        p.setNametagHealth(new Color(50, 220, 120).getRGB());
        p.setParticlePrimary(new Color(50, 220, 120).getRGB());
        p.setCategoryCombat(new Color(255, 100, 100).getRGB());
        p.setCategoryMovement(p.getPrimary());
        p.setCategoryRender(p.getSecondary());
        p.setCategoryPlayer(new Color(200, 220, 80).getRGB());
        p.setCategoryWorld(new Color(100, 150, 80).getRGB());
        return new Theme("Emerald", "Fresh green with teal undertones", p);
    }

    private static Theme createSakura() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(255, 150, 255).getRGB());
        p.setSecondary(new Color(255, 200, 150).getRGB());
        p.setTertiary(new Color(200, 150, 255).getRGB());
        p.setBackground(new Color(18, 12, 16).getRGB());
        p.setSurface(new Color(30, 18, 24).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(180, 140, 160).getRGB());
        p.setTextAccent(new Color(255, 200, 220).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(22, 14, 18, 255).getRGB());
        p.setTargetHudHealth(new Color(255, 120, 170).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getTertiary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.35f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.60f));
        p.setGlow(new Color(255, 150, 200, 255).getRGB());
        p.setBlurColor(new Color(30, 18, 24, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getTertiary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(50, 30, 40).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(130, 70, 100).getRGB());
        p.setNotificationSuccess(new Color(180, 255, 180).getRGB());
        p.setNotificationError(new Color(255, 80, 80).getRGB());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(40, 22, 30, 255).getRGB());
        p.setNametagHealth(new Color(255, 120, 170).getRGB());
        p.setParticlePrimary(new Color(255, 150, 255).getRGB());
        p.setCategoryCombat(new Color(255, 100, 120).getRGB());
        p.setCategoryMovement(new Color(150, 255, 180).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(255, 230, 120).getRGB());
        p.setCategoryWorld(p.getTertiary());
        p.setAnimated(true);
        p.setSpeed(0.6f);
        return new Theme("Sakura", "Soft cherry blossom pink tones", p);
    }

    private static Theme createMidnight() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(80, 100, 255).getRGB());
        p.setSecondary(new Color(120, 60, 220).getRGB());
        p.setTertiary(new Color(60, 180, 255).getRGB());
        p.setBackground(new Color(6, 6, 14).getRGB());
        p.setSurface(new Color(12, 12, 24).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(100, 100, 160).getRGB());
        p.setTextAccent(new Color(140, 140, 160).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(8, 8, 20, 255).getRGB());
        p.setTargetHudHealth(new Color(100, 120, 255).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getTertiary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.25f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.50f));
        p.setGlow(new Color(80, 100, 255, 255).getRGB());
        p.setBlurColor(new Color(12, 12, 24, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getSecondary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(20, 20, 40).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(40, 40, 100).getRGB());
        p.setNotificationSuccess(new Color(80, 200, 255).getRGB());
        p.setNotificationError(new Color(255, 60, 100).getRGB());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(14, 14, 30, 255).getRGB());
        p.setNametagHealth(new Color(100, 120, 255).getRGB());
        p.setParticlePrimary(new Color(80, 100, 255).getRGB());
        p.setCategoryCombat(new Color(255, 80, 100).getRGB());
        p.setCategoryMovement(new Color(80, 200, 120).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(180, 180, 80).getRGB());
        p.setCategoryWorld(p.getSecondary());
        p.setGlowIntensity(1.8f);
        return new Theme("Midnight", "Deep dark blue with royal purple", p);
    }

    private static Theme createCottonCandy() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(180, 200, 255).getRGB());
        p.setSecondary(new Color(255, 180, 220).getRGB());
        p.setTertiary(new Color(200, 230, 255).getRGB());
        p.setBackground(new Color(14, 14, 22).getRGB());
        p.setSurface(new Color(22, 20, 30).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(160, 150, 180).getRGB());
        p.setTextAccent(new Color(200, 210, 255).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(16, 16, 26, 255).getRGB());
        p.setTargetHudHealth(new Color(255, 180, 220).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getSecondary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.30f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.55f));
        p.setGlow(new Color(180, 200, 255, 255).getRGB());
        p.setBlurColor(new Color(22, 20, 30, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getSecondary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(35, 30, 45).getRGB());
        p.setToggleOn(new Color(150, 200, 255).getRGB());
        p.setToggleOff(new Color(100, 80, 130).getRGB());
        p.setNotificationSuccess(new Color(150, 220, 255).getRGB());
        p.setNotificationError(new Color(255, 100, 130).getRGB());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(28, 24, 38, 255).getRGB());
        p.setNametagHealth(new Color(255, 180, 220).getRGB());
        p.setParticlePrimary(new Color(180, 200, 255).getRGB());
        p.setCategoryCombat(new Color(255, 140, 255).getRGB());
        p.setCategoryMovement(new Color(160, 220, 180).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(220, 220, 140).getRGB());
        p.setCategoryWorld(new Color(180, 140, 220).getRGB());
        p.setAnimated(true);
        p.setSpeed(0.4f);
        return new Theme("Cotton Candy", "Soft pastel blue and pink", p);
    }

    private static Theme createRgbDynamic() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(255, 50, 50).getRGB());
        p.setSecondary(new Color(50, 255, 50).getRGB());
        p.setTertiary(new Color(50, 50, 255).getRGB());
        p.setBackground(new Color(8, 8, 14).getRGB());
        p.setSurface(new Color(16, 16, 26).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(140, 140, 180).getRGB());
        p.setTextAccent(new Color(200, 200, 255).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(Color.WHITE.getRGB());
        p.setTargetHudBackground(new Color(10, 10, 20, 255).getRGB());
        p.setTargetHudHealth(new Color(255, 50, 50).getRGB());
        p.setTargetHudAccent(Color.WHITE.getRGB());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(Color.WHITE.getRGB());
        p.setCircleEsp(Color.WHITE.getRGB());
        p.setSpirits(Color.WHITE.getRGB());
        p.setWingsPrimary(Color.WHITE.getRGB());
        p.setWingsSecondary(new Color(200, 200, 255).getRGB());
        p.setWingsGlow(Color.WHITE.getRGB());
        p.setGlow(new Color(255, 255, 255, 255).getRGB());
        p.setBlurColor(new Color(16, 16, 26, 255).getRGB());
        p.setGradientStart(new Color(255, 50, 50).getRGB());
        p.setGradientEnd(new Color(50, 50, 255).getRGB());
        p.setProgressBar(Color.WHITE.getRGB());
        p.setProgressBarBackground(new Color(30, 30, 45).getRGB());
        p.setToggleOn(new Color(50, 255, 50).getRGB());
        p.setToggleOff(new Color(255, 50, 50).getRGB());
        p.setNotificationSuccess(new Color(50, 255, 50).getRGB());
        p.setNotificationError(new Color(255, 50, 50).getRGB());
        p.setNotificationInfo(Color.WHITE.getRGB());
        p.setNametagBackground(new Color(20, 20, 36, 255).getRGB());
        p.setNametagHealth(new Color(255, 80, 80).getRGB());
        p.setParticlePrimary(Color.WHITE.getRGB());
        p.setCategoryCombat(new Color(255, 80, 80).getRGB());
        p.setCategoryMovement(new Color(80, 255, 80).getRGB());
        p.setCategoryRender(new Color(89, 255, 231).getRGB());
        p.setCategoryPlayer(new Color(255, 255, 80).getRGB());
        p.setCategoryWorld(new Color(200, 80, 255).getRGB());
        p.setRainbow(true);
        p.setSpeed(1.0f);
        p.setSaturation(0.9f);
        p.setBrightness(1.0f);
        p.setGlowIntensity(1.5f);
        return new Theme("RGB Dynamic", "Full RGB cycling through all colors", p);

    }

    private static Theme createLava() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(255, 120, 20).getRGB());
        p.setSecondary(new Color(220, 40, 40).getRGB());
        p.setTertiary(new Color(255, 220, 50).getRGB());
        p.setBackground(new Color(16, 8, 6).getRGB());
        p.setSurface(new Color(28, 14, 10).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(200, 160, 120).getRGB());
        p.setTextAccent(new Color(255, 200, 100).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(20, 10, 8, 255).getRGB());
        p.setTargetHudHealth(new Color(255, 80, 40).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getTertiary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.25f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.50f));
        p.setGlow(new Color(255, 120, 20, 255).getRGB());
        p.setBlurColor(new Color(28, 14, 10, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getSecondary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(50, 25, 18).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(120, 50, 30).getRGB());
        p.setNotificationSuccess(new Color(255, 200, 50).getRGB());
        p.setNotificationError(new Color(255, 40, 40).getRGB());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(38, 18, 14, 255).getRGB());
        p.setNametagHealth(new Color(255, 80, 40).getRGB());
        p.setParticlePrimary(new Color(255, 120, 20).getRGB());
        p.setCategoryCombat(new Color(255, 60, 60).getRGB());
        p.setCategoryMovement(new Color(255, 200, 50).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(255, 180, 80).getRGB());
        p.setCategoryWorld(p.getTertiary());
        p.setAnimated(true);
        p.setSpeed(0.7f);
        return new Theme("Lava", "Molten orange and red volcanic tones", p);
    }

    private static Theme createArctic() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(150, 220, 255).getRGB());
        p.setSecondary(new Color(200, 230, 255).getRGB());
        p.setTertiary(new Color(100, 180, 230).getRGB());
        p.setBackground(new Color(8, 12, 18).getRGB());
        p.setSurface(new Color(14, 20, 30).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(150, 180, 200).getRGB());
        p.setTextAccent(new Color(180, 230, 255).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(10, 16, 24, 255).getRGB());
        p.setTargetHudHealth(new Color(150, 220, 255).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getSecondary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.30f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.55f));
        p.setGlow(new Color(150, 220, 255, 255).getRGB());
        p.setBlurColor(new Color(14, 20, 30, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getTertiary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(25, 35, 50).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(40, 60, 90).getRGB());
        p.setNotificationSuccess(new Color(100, 220, 255).getRGB());
        p.setNotificationError(new Color(200, 80, 80).getRGB());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(18, 26, 38, 255).getRGB());
        p.setNametagHealth(new Color(150, 220, 255).getRGB());
        p.setParticlePrimary(new Color(180, 230, 255).getRGB());
        p.setCategoryCombat(new Color(150, 180, 255).getRGB());
        p.setCategoryMovement(new Color(150, 255, 220).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(200, 220, 180).getRGB());
        p.setCategoryWorld(new Color(180, 180, 255).getRGB());
        p.setGlowIntensity(0.8f);
        return new Theme("Arctic", "Cold ice blue and frosty white", p);
    }

    private static Theme createToxic() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(50, 255, 80).getRGB());
        p.setSecondary(new Color(180, 255, 0).getRGB());
        p.setTertiary(new Color(0, 200, 50).getRGB());
        p.setBackground(new Color(6, 14, 8).getRGB());
        p.setSurface(new Color(12, 24, 14).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(120, 200, 140).getRGB());
        p.setTextAccent(new Color(180, 255, 150).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(8, 18, 10, 255).getRGB());
        p.setTargetHudHealth(new Color(50, 255, 80).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getSecondary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.25f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.50f));
        p.setGlow(new Color(50, 255, 80, 255).getRGB());
        p.setBlurColor(new Color(12, 24, 14, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getSecondary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(18, 40, 22).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(30, 100, 40).getRGB());
        p.setNotificationSuccess(p.getPrimary());
        p.setNotificationError(new Color(255, 60, 60).getRGB());
        p.setNotificationInfo(p.getSecondary());
        p.setNametagBackground(new Color(16, 32, 20, 255).getRGB());
        p.setNametagHealth(new Color(50, 255, 80).getRGB());
        p.setParticlePrimary(new Color(50, 255, 80).getRGB());
        p.setCategoryCombat(new Color(255, 80, 80).getRGB());
        p.setCategoryMovement(p.getPrimary());
        p.setCategoryRender(p.getSecondary());
        p.setCategoryPlayer(new Color(200, 255, 80).getRGB());
        p.setCategoryWorld(new Color(120, 200, 80).getRGB());
        p.setAnimated(true);
        p.setSpeed(0.9f);
        return new Theme("Toxic", "Neon green radioactive waste", p);
    }

    private static Theme createAmethyst() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(160, 80, 255).getRGB());
        p.setSecondary(new Color(220, 80, 255).getRGB());
        p.setTertiary(new Color(100, 60, 200).getRGB());
        p.setBackground(new Color(12, 8, 20).getRGB());
        p.setSurface(new Color(20, 14, 32).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(160, 120, 200).getRGB());
        p.setTextAccent(new Color(200, 160, 255).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(14, 10, 26, 255).getRGB());
        p.setTargetHudHealth(new Color(220, 80, 255).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getTertiary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.30f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.55f));
        p.setGlow(new Color(160, 80, 255, 255).getRGB());
        p.setBlurColor(new Color(20, 14, 32, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getTertiary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(35, 25, 50).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(80, 40, 130).getRGB());
        p.setNotificationSuccess(new Color(180, 200, 255).getRGB());
        p.setNotificationError(new Color(255, 60, 100).getRGB());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(26, 18, 40, 255).getRGB());
        p.setNametagHealth(new Color(220, 80, 255).getRGB());
        p.setParticlePrimary(new Color(200, 150, 255).getRGB());
        p.setCategoryCombat(new Color(255, 100, 180).getRGB());
        p.setCategoryMovement(new Color(150, 200, 255).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(200, 200, 100).getRGB());
        p.setCategoryWorld(new Color(150, 100, 255).getRGB());
        return new Theme("Amethyst", "Rich purple crystal gemstone tones", p);
    }

    private static Theme createChocolate() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(180, 120, 70).getRGB());
        p.setSecondary(new Color(220, 160, 100).getRGB());
        p.setTertiary(new Color(120, 70, 40).getRGB());
        p.setBackground(new Color(14, 10, 8).getRGB());
        p.setSurface(new Color(24, 18, 14).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(180, 150, 120).getRGB());
        p.setTextAccent(new Color(220, 190, 140).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(18, 12, 10, 255).getRGB());
        p.setTargetHudHealth(new Color(220, 160, 100).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getTertiary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.20f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.45f));
        p.setGlow(new Color(180, 120, 70, 255).getRGB());
        p.setBlurColor(new Color(24, 18, 14, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getTertiary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(45, 30, 22).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(90, 60, 40).getRGB());
        p.setNotificationSuccess(new Color(180, 200, 100).getRGB());
        p.setNotificationError(new Color(200, 80, 60).getRGB());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(32, 22, 18, 255).getRGB());
        p.setNametagHealth(new Color(220, 160, 100).getRGB());
        p.setParticlePrimary(new Color(180, 120, 70).getRGB());
        p.setCategoryCombat(new Color(200, 80, 60).getRGB());
        p.setCategoryMovement(new Color(180, 200, 100).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(200, 180, 80).getRGB());
        p.setCategoryWorld(new Color(160, 100, 140).getRGB());
        p.setAnimated(true);
        p.setSpeed(0.5f);
        return new Theme("Chocolate", "Warm brown and caramel sweet tones", p);
    }

    private static Theme createBloodMoon() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(200, 20, 20).getRGB());
        p.setSecondary(new Color(140, 10, 10).getRGB());
        p.setTertiary(new Color(255, 60, 30).getRGB());
        p.setBackground(new Color(10, 6, 8).getRGB());
        p.setSurface(new Color(20, 12, 14).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(180, 100, 100).getRGB());
        p.setTextAccent(new Color(255, 120, 100).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(14, 8, 10, 255).getRGB());
        p.setTargetHudHealth(new Color(255, 40, 40).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(new Color(100, 10, 10).getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(new Color(180, 30, 30).getRGB());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.15f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.40f));
        p.setGlow(new Color(200, 20, 20, 255).getRGB());
        p.setBlurColor(new Color(20, 12, 14, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(new Color(80, 0, 0).getRGB());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(40, 18, 18).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(100, 20, 20).getRGB());
        p.setNotificationSuccess(new Color(100, 180, 100).getRGB());
        p.setNotificationError(p.getPrimary());
        p.setNotificationInfo(p.getTertiary());
        p.setNametagBackground(new Color(30, 14, 16, 255).getRGB());
        p.setNametagHealth(new Color(255, 40, 40).getRGB());
        p.setParticlePrimary(new Color(200, 20, 20).getRGB());
        p.setCategoryCombat(p.getPrimary());
        p.setCategoryMovement(new Color(150, 50, 50).getRGB());
        p.setCategoryRender(p.getTertiary());
        p.setCategoryPlayer(new Color(200, 100, 60).getRGB());
        p.setCategoryWorld(new Color(100, 40, 100).getRGB());
        p.setGlowIntensity(2.0f);
        return new Theme("Blood Moon", "Deep blood red with dark eerie tones", p);
    }

    private static Theme createCyberpunk() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(255, 0, 180).getRGB());
        p.setSecondary(new Color(0, 180, 255).getRGB());
        p.setTertiary(new Color(255, 220, 0).getRGB());
        p.setBackground(new Color(6, 6, 16).getRGB());
        p.setSurface(new Color(12, 10, 26).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(140, 130, 200).getRGB());
        p.setTextAccent(new Color(200, 180, 255).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(8, 8, 22, 255).getRGB());
        p.setTargetHudHealth(new Color(255, 0, 180).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getSecondary());
        p.setSpirits(p.getPrimary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.25f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.50f));
        p.setGlow(new Color(255, 0, 180, 255).getRGB());
        p.setBlurColor(new Color(12, 10, 26, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getSecondary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(25, 20, 45).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(80, 20, 100).getRGB());
        p.setNotificationSuccess(new Color(0, 255, 200).getRGB());
        p.setNotificationError(new Color(255, 30, 60).getRGB());
        p.setNotificationInfo(p.getSecondary());
        p.setNametagBackground(new Color(16, 14, 34, 255).getRGB());
        p.setNametagHealth(new Color(255, 0, 180).getRGB());
        p.setParticlePrimary(new Color(255, 0, 180).getRGB());
        p.setCategoryCombat(new Color(255, 30, 80).getRGB());
        p.setCategoryMovement(new Color(0, 255, 200).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(255, 220, 0).getRGB());
        p.setCategoryWorld(p.getSecondary());
        p.setAnimated(true);
        p.setSpeed(1.2f);
        p.setGlowIntensity(2.0f);
        return new Theme("Cyberpunk", "Neon pink and cyan futuristic city", p);
    }

    private static Theme createAurora() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(80, 255, 150).getRGB());
        p.setSecondary(new Color(180, 80, 255).getRGB());
        p.setTertiary(new Color(0, 255, 200).getRGB());
        p.setBackground(new Color(6, 10, 16).getRGB());
        p.setSurface(new Color(12, 18, 28).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(140, 180, 180).getRGB());
        p.setTextAccent(new Color(160, 255, 200).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(8, 14, 22, 255).getRGB());
        p.setTargetHudHealth(new Color(80, 255, 150).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getSecondary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.30f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.55f));
        p.setGlow(new Color(80, 255, 150, 255).getRGB());
        p.setBlurColor(new Color(12, 18, 28, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getSecondary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(18, 30, 40).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(30, 80, 70).getRGB());
        p.setNotificationSuccess(new Color(80, 220, 160).getRGB());
        p.setNotificationError(new Color(255, 80, 100).getRGB());
        p.setNotificationInfo(p.getSecondary());
        p.setNametagBackground(new Color(16, 24, 36, 255).getRGB());
        p.setNametagHealth(new Color(80, 255, 150).getRGB());
        p.setParticlePrimary(new Color(80, 255, 150).getRGB());
        p.setCategoryCombat(new Color(180, 120, 255).getRGB());
        p.setCategoryMovement(p.getPrimary());
        p.setCategoryRender(p.getTertiary());
        p.setCategoryPlayer(new Color(200, 220, 100).getRGB());
        p.setCategoryWorld(p.getSecondary());
        p.setAnimated(true);
        p.setSpeed(0.6f);
        return new Theme("Aurora", "Northern lights green and purple", p);
    }

    private static Theme createHarvest() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(230, 140, 30).getRGB());
        p.setSecondary(new Color(230, 200, 50).getRGB());
        p.setTertiary(new Color(160, 90, 40).getRGB());
        p.setBackground(new Color(16, 12, 8).getRGB());
        p.setSurface(new Color(28, 20, 14).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(200, 170, 120).getRGB());
        p.setTextAccent(new Color(255, 210, 120).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(20, 14, 10, 255).getRGB());
        p.setTargetHudHealth(new Color(230, 140, 30).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(Color.WHITE.getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getTertiary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.25f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.50f));
        p.setGlow(new Color(230, 140, 30, 255).getRGB());
        p.setBlurColor(new Color(28, 20, 14, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getTertiary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(45, 30, 20).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(120, 70, 30).getRGB());
        p.setNotificationSuccess(new Color(180, 220, 80).getRGB());
        p.setNotificationError(new Color(200, 80, 50).getRGB());
        p.setNotificationInfo(p.getPrimary());
        p.setNametagBackground(new Color(36, 24, 18, 255).getRGB());
        p.setNametagHealth(new Color(230, 140, 30).getRGB());
        p.setParticlePrimary(new Color(230, 200, 50).getRGB());
        p.setCategoryCombat(new Color(200, 80, 50).getRGB());
        p.setCategoryMovement(new Color(180, 220, 80).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(230, 200, 50).getRGB());
        p.setCategoryWorld(new Color(160, 90, 40).getRGB());
        return new Theme("Harvest", "Warm autumn orange and gold harvest", p);
    }

    private static Theme createVoid() {
        ThemeColorPalette p = new ThemeColorPalette();
        p.setPrimary(new Color(100, 40, 160).getRGB());
        p.setSecondary(new Color(60, 20, 100).getRGB());
        p.setTertiary(new Color(140, 60, 200).getRGB());
        p.setBackground(new Color(4, 4, 10).getRGB());
        p.setSurface(new Color(10, 8, 18).getRGB());
        p.setTextPrimary(Color.WHITE.getRGB());
        p.setTextSecondary(new Color(100, 80, 140).getRGB());
        p.setTextAccent(new Color(160, 120, 200).getRGB());
        p.setHudBackground(new Color(151, 142, 142, 255).getRGB());
        p.setHudText(Color.WHITE.getRGB());
        p.setHudAccent(p.getPrimary());
        p.setTargetHudBackground(new Color(6, 6, 14, 255).getRGB());
        p.setTargetHudHealth(new Color(140, 60, 200).getRGB());
        p.setTargetHudAccent(p.getPrimary());
        p.setTargetEspFill(new Color(30, 10, 50).getRGB());
        p.setTargetEspLine(p.getPrimary());
        p.setCircleEsp(p.getPrimary());
        p.setSpirits(p.getTertiary());
        p.setWingsPrimary(p.getPrimary());
        p.setWingsSecondary(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.20f));
        p.setWingsGlow(ColorProvider.interpolateColor(p.getPrimary(), Color.WHITE.getRGB(), 0.45f));
        p.setGlow(new Color(100, 40, 160, 255).getRGB());
        p.setBlurColor(new Color(10, 8, 18, 255).getRGB());
        p.setGradientStart(p.getPrimary());
        p.setGradientEnd(p.getSecondary());
        p.setProgressBar(p.getPrimary());
        p.setProgressBarBackground(new Color(20, 15, 35).getRGB());
        p.setToggleOn(p.getPrimary());
        p.setToggleOff(new Color(40, 20, 70).getRGB());
        p.setNotificationSuccess(new Color(100, 180, 255).getRGB());
        p.setNotificationError(new Color(200, 30, 100).getRGB());
        p.setNotificationInfo(p.getTertiary());
        p.setNametagBackground(new Color(14, 12, 26, 255).getRGB());
        p.setNametagHealth(new Color(140, 60, 200).getRGB());
        p.setParticlePrimary(new Color(100, 40, 160).getRGB());
        p.setCategoryCombat(new Color(180, 40, 120).getRGB());
        p.setCategoryMovement(new Color(60, 120, 200).getRGB());
        p.setCategoryRender(p.getPrimary());
        p.setCategoryPlayer(new Color(140, 100, 80).getRGB());
        p.setCategoryWorld(new Color(80, 40, 120).getRGB());
        p.setGlowIntensity(0.5f);
        return new Theme("Void", "Deep dark purple from the abyss", p);
    }
}

